name: Test Cross Platform Support

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Extract Example File on Ubuntu
    steps:
      - uses: actions/checkout@v3.4.0 
      - run: docker build -t example:${{ github.sha }} ./.github/tests
      - uses: ./
        id: extract
        with:
          image: example:${{ github.sha }}
          path: /files/001.txt
      - run: test -e ${{ steps.extract.outputs.destination }}/001.txt || exit 1
  macos:
    runs-on: macos-latest

    name: Extract Example File on macOS
    steps:
      - uses: actions/checkout@v3.4.0 
      - name: Install Docker
        env:
          HOMEBREW_GITHUB_API_TOKEN: "${{ github.token }}"
        run: |
          brew install docker colima
          colima start
      - run: docker build -t example:${{ github.sha }} ./.github/tests
      - uses: ./
        id: extract
        with:
          image: example:${{ github.sha }}
          path: /files/001.txt
      - run: test -e ${{ steps.extract.outputs.destination }}/001.txt || exit 1
  
